### ISSUE TITLE
If someone is left alone at the party, let the party disband

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapiparties#1]
If someone is left alone at the party, let the party disband

now:
Even if someone is left alone in the party, the party goes on.

**Comment by Sentropic** [comment]
This wouldn't guarantee that parties are always composed of at least two players: When a player who is not in a party invites another, a party composed only by the inviting player is created, to handle the invitation.

Is there a particular reason why you need to disband parties with lone players?
