### ISSUE TITLE
Parties Papi Support

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/proskillapiparties#12]
There are a few. Making a list of them now

**Comment by DrHeretic** [comment]
Must have's to expand player use of party scoreboards with other plugins or U.I.

%Party_Member_Player%
%Party_Member_HP%
%Party_Member_MP%
%Party_Exp_Bonus%
%Party_Leader%
%Player_Debuff%

Optional--

%Party_Location%
%Player_Debuff%

**Comment by Sentropic** [comment]
What would you expect to be returned by each of those? The only one clear to me is %Party_Leader%

**Comment by DrHeretic** [comment]
Well, in most cases being able to party and see the others HP/MP limits in a scoreboard or when using a UI you can add a party section that shows the others hp/mp limits.

Think along the sides of being in world of warcraft and ffxiv. When you are in a party with anyone it would be hella annoying trying to heal everyone and you cant see what their current hp limits, and if have to look around for the person who may be out of sight  you to notice their HP limits they end up dying because they are around the corner getting mobbed on.

%party_member_player% so you also know who's HP is currently low. 

%Player_Debuff% is in the range of helping know what is currently on a party member and what the others or healer could do to cleanse them.

**Comment by lordsrubka5** [comment]
%party_name_1% name of the 1st person in the members list

%party_health_1% - returns hp of the 1st person in the members list

%party_maxhealth_1%  - returns max hp of 1st person

%party_healthp_1% - returns current hp/maxhp %

Same for mana im lazy to type

%party_exp_bonus% - rerurns the actual number of the exp bonus from the config so that normal players can see the benefits
(Config is 0-1 so it should be made so the placeholder returns the % increase from the equally split exp)

Later on for some advanced time would be nice to be able to parse party members statuses like buffs and debuffs but I wouldnt go into that now since thats not even a thing for a single player

**Comment by Sentropic** [comment]
@lordsrubka5 that's what I actually needed, thx. Does doing like that make sense to you @DrHeretic, with member numbers?

**Comment by lordsrubka5** [comment]
member numbers would be like in what order they are in /pt info, by default leader should be 1st unless the party is so old that the leader left and gave to someone else. In that case either reordering party members on swapping leaders or a built in unicode crown (ability to change icon in config) that shows up in front of %party_name_(number)% if they are the leader

**Comment by DrHeretic** [comment]
@Sentropic  Yes i forgot about adding that when putting up my examples. number will help alot for placement

**Comment by Sentropic** [comment]
Global placeholders:
`%sapiparty_max_size%`
`%sapiparty_invite_timeout%`
`%sapiparty_exp_share_radius%`
`%sapiparty_exp_member_modifier%`
`%sapiparty_exp_level_modifier%`
`%sapiparty_item_share_radius%`

Placeholders for players in a Party:
`%sapiparty_leader_name%`
`%sapiparty_leader_uuid%`
`%sapiparty_size%`
`%sapiparty_name_<pos>%`
`%sapiparty_uuid_<pos>%`

where `<pos>` is the index of the player in a party, starting at 1.

After https://github.com/promcteam/proskillapi/commit/6368df9d1882f290600229068d9b417a36ae38c3, mana and health for teammates can be obtained from ProSkillAPI's placeholders, for example:
`%sapi_default_currentmana_{sapiparty_uuid_<pos>}%`
A list of available ProSkillAPI's placeholders can be found [here](https://promcteam.com/wiki/index.php/Proskillapi:Placeholders). You just have to add the `_{sapiparty_uuid_<pos>}` at the end.

**Comment by Sentropic** [comment]
The debuffs placeholder is a ProSkillAPI feature, not a parties one, so it will be done separetely in the future.
The location one is a feature of the [OtherPlayer](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#otherplayer) PAPI expansion, but currently doesn't support nested placeholders, so I might make it for ProSkillAPI too.
