### ISSUE TITLE
**[BUG]** Party leader not swapped after leaving party

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapiparties#9]
After party leader leaves the party, his name is still on the party info leader section

**Comment by Travja** [comment]
As near as I can tell, this should only be the case if there are no other _online_ players to take the leader spot. I'm going to try updating a couple things and we can see if that fixes things, but could you confirm that this happens any time a party leader leaves the party?

**Comment by Travja** [comment]
If you want to try the newest build, I think that'll actually work.
